### ISSUE TITLE
Position of Popover

### ISSUE THREAD

**Issue by Florian9-3** [ajayparsana/ionic-autocomplete#1]
I assume the vertical position of the popover should be below the input element. However on iOS the popover starts at the top of the screen. If I close the keyboard it moves down the height of keyboard.

On Android the Popover is displayed nearly correctly (had to do some modifications. However, when I close the keyboard the position does not update.

Idea for the keyboard hide/show error: Event listener for keyboard show/hide -> recalculate the position of the popover.

**Comment by seatechdev** [comment]
did you have any luck with this?  I am trying to edit the popover to make its width equal to the search box.
