### ISSUE TITLE
autocompleteInputAsync - Result list never shows up for a custom API

### ISSUE THREAD

**Issue by seatechdev** [ajayparsana/ionic-autocomplete#2]
OS:  iOS
I first tested this with the service that is provided in the Demo code https://restcountries.eu/rest/v1/name/india and it works fine in the app.  Then pointed it to my own custom restufl API.  Changed the name 'propNameToDisplay':  to 'retail_product_name', from 'name'

I can see the results in my Xcode console but list never appears in the app and Selected Item: shows whatever I type in the input box.    My database is fairly large therefore I cannot load it all at once for a synchronous call.  

Any suggestions how can I make this work?

**Comment by seatechdev** [comment]
Got it working.  The issue was in my api code.  Thank you for your attention and responding to my email.

**Comment by ajayparsana** [comment]
Closing this as issue is fixed
